### ISSUE TITLE
脚本文件格式的问题

### ISSUE THREAD

**Issue by Joker1995** [TeamcatCorp/Teamcat#1]
build_shell下的包.sh通过git clone后为window格式,需要用notepad++转unix格式,另外redis.sh需要在cd $dir/redis-3.2.8/src/后边加chmod +x

Teamcat/distribute/0.0.1/build_shell/teamcat/doraemon/settings.py
102行的ALIAS:'teamcat',需要改为'default'

**Comment by SiyuanLu2012** [comment]
好的，已修复，感谢您宝贵的建议。git clone后文件的格式问题其他人如果无法运行脚本请注意下此点，我们确实提交的是unix格式，可能是git下载过程中出现的问题。
